languageCode = "en"
languageName = "English"
weight = 1
title = "Zach Le"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/icon.png"
copyright = "{ year } Zachary Le"
description = "Zachary Le's portfolio and blog"
secondaryLogo = "img/icon.png"

[params.author]
name = "Zach Le"
image = "img/pfp.png"
headline = "Systems Administrator"
bio = "Transforming my server rack into a jet engine"
links = [ { email = "mailto:hello@zachle.info" }, { github = "https://github.com/zle3" }, { linkedin = "https://linkedin.com/in/zle" }, { youtube = "https://youtube.com/@Zachary-Le" }, { bluesky = "https://bsky.app/profile/zachle.info" } ]
