[[main]]
none = "none"

[[main]]
name = "Resume"
pageRef = "resume"
weight = 10

[[main]]
name = "About"
pageRef = "about"
weight = 20

[[main]]
name = "Portfolio"
pageRef = "portfolio"
weight = 30

[[main]]
name = "Now"
pageRef = "now"
weight = 40

[[main]]
name = "Blog"
pageRef = "blog"
weight = 50

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "About"
pageRef = "about"
weight = 20