colorScheme = "zli-ppr-custom"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
mainSections = "Blog"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/blog"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showZenMode = false
article.showRelatedContent = true

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = true
showCards = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
showViews = true
showLikes = true
firebase.apiKey = "$FIREBASE_API_KEY"
firebase.authDomain = "$FIREBASE_AUTH_DOMAIN"
firebase.projectId = "$FIREBASE_PROJECT_ID"
firebase.storageBucket = "$FIREBASE_STORAGE_BUCKET"
firebase.messagingSenderId = "$FIREBASE_MESSAGING_SENDER_ID"
firebase.appId = "$FIREBASE_APP_ID"
firebase.measurementId = "$FIREBASE_MEASUREMENT_ID"

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
